Timirbaev Project - Courier Management System: TimirbaevPark Class Reference
TimirbaevPark Class Reference
#include <timirbaevpark.h>
Public Member Functions
void AddCourier (Ui::TimirbaevAddDialog *ui)
void AddAutoCourier (Ui::TimirbaevAddDialog *ui)
void DeleteCouriers ()
void SaveSer ()
bool LoadSer ()
std::vector< std::shared_ptr< TimirbaevCourier > > & GetCouriers ()
~TimirbaevPark ()
Private Attributes
std::vector< std::shared_ptr< TimirbaevCourier > > couriers
Detailed Description
Definition at line 23 of file timirbaevpark.h.
Constructor & Destructor Documentation
~TimirbaevPark()
TimirbaevPark::~TimirbaevPark () inline
Definition at line 35 of file timirbaevpark.h.
                     {
        DeleteCouriers();
    }
References DeleteCouriers().
Member Function Documentation
AddAutoCourier()
void TimirbaevPark::AddAutoCourier (Ui::TimirbaevAddDialog * ui)
Definition at line 17 of file timirbaevpark.cpp.
{
    std::shared_ptr<TimirbaevAutoCourier> ptr = std::make_shared<TimirbaevAutoCourier>();
    ptr->CreateCourier(ui);
    couriers.push_back(ptr);
}
References couriers.
Referenced by TimirbaevAddDialog::on_pushButton_clicked().
AddCourier()
void TimirbaevPark::AddCourier (Ui::TimirbaevAddDialog * ui)
Definition at line 11 of file timirbaevpark.cpp.
{
    std::shared_ptr<TimirbaevCourier> ptr = std::make_shared<TimirbaevCourier>();
    ptr->CreateCourier(ui);
    couriers.push_back(ptr);
}
Referenced by TimirbaevAddDialog::on_pushButton_clicked().
DeleteCouriers()
void TimirbaevPark::DeleteCouriers ()
Definition at line 23 of file timirbaevpark.cpp.
{
    couriers.clear();
    std::cout << "Список очищен.\n";
}
References couriers.
Referenced by LoadSer(), TimirbaevMainWindow::on_actionClear_triggered(), and ~TimirbaevPark().
GetCouriers()
std::vector< std::shared_ptr< TimirbaevCourier > > & TimirbaevPark::GetCouriers ()
Definition at line 28 of file timirbaevpark.cpp.
{
    return couriers;
}
References couriers.
Referenced by TimirbaevMainWindow::on_actionEdit_triggered(), TimirbaevDialog::TimirbaevDialog(), and TimirbaevTable::TimirbaevTable().
LoadSer()
bool TimirbaevPark::LoadSer ()
Definition at line 48 of file timirbaevpark.cpp.
{
    std::string fileName = QFileDialog::getOpenFileName(nullptr, "Открыть файл", "", "Текстовые файлы (*.txt);;Все файлы (*.*)").toStdString();
    if (fileName.empty()) {
        QMessageBox::information(nullptr, "Информация", "Файл не выбран.");
        return 0;
    }
    DeleteCouriers();
    std::ifstream fin(fileName);
    if (fin) {
        try {
            boost::archive::text_iarchive ia(fin);
            ia >> couriers;
            QMessageBox::information(nullptr, "Успех", "Данные загружены.");
            fin.close();
            return 1;
        } catch (const std::exception& e) {
            QMessageBox::information(nullptr, "Ошибка", "Не удалось считать данные.");
            DeleteCouriers();
            fin.close();
            return 0;
        }
    }
    else return 0;
}
References couriers, and DeleteCouriers().
Referenced by TimirbaevMainWindow::on_actionLoad_triggered().
SaveSer()
void TimirbaevPark::SaveSer ()
Definition at line 32 of file timirbaevpark.cpp.
{
    std::string fileName = QFileDialog::getSaveFileName(nullptr, "Сохранить файл", "", "Текстовые файлы (*.txt);;Все файлы (*.*)").toStdString();
    if (fileName.empty()) {
        QMessageBox::information(nullptr, "Информация", "Файл не выбран.");
    }
    std::ofstream fout(fileName);
    if (fout) {
        boost::archive::text_oarchive oa(fout);
        oa << couriers;
        QMessageBox::information(nullptr, "Успех", "Файл успешно сохранён.");
        fout.close();
    }
}
References couriers.
Referenced by TimirbaevMainWindow::on_actionSave_triggered().
Member Data Documentation
couriers
std::vector<std::shared_ptr<TimirbaevCourier> > TimirbaevPark::couriers private
Definition at line 25 of file timirbaevpark.h.
Referenced by AddAutoCourier(), DeleteCouriers(), GetCouriers(), LoadSer(), and SaveSer().
The documentation for this class was generated from the following files:
timirbaevpark.h
timirbaevpark.cpp