Timirbaev Project - Courier Management System: timirbaevutilities.h File Reference
timirbaevutilities.h File Reference
#include <iostream>
#include <string>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <boost/serialization/version.hpp>
#include <boost/serialization/split_member.hpp>
Functions
bool IntCheck (std::string input)
int GetCorrectNumber (int min, int max)
Function Documentation
GetCorrectNumber()
int GetCorrectNumber (int min, int max) inline
Definition at line 25 of file timirbaevutilities.h.
{
    std::string num;
    while ((std::getline(std::cin, num)).fail() || IntCheck(num) == false || stoi(num) < min || stoi(num) > max) {
        std::cout << "Введите номер от " << min << " до " << max << ": ";
    }
    return stoi(num);
}
References IntCheck().
IntCheck()
bool IntCheck (std::string input) inline
Definition at line 16 of file timirbaevutilities.h.
{
    for (int i = 0; i < input.length(); i++) {
        if (isdigit((unsigned char)input[i])) continue;
        else return false;
    }
    if (input.length() == 0) return false;
    return true;
}
Referenced by GetCorrectNumber(), and TimirbaevAddDialog::on_pushButton_clicked().