Timirbaev Project - Courier Management System: TimirbaevAutoCourier Class Reference
TimirbaevAutoCourier Class Reference
#include <timirbaevautocourier.h>
Public Member Functions
TimirbaevAutoCourier ()
void CreateCourier (Ui::TimirbaevAddDialog *ui) override
void ShowCourier (QPainter &painter, int &i) const override
void ViewCourier (Ui::TimirbaevDialog *ui) const override
void EditCourier (Ui::TimirbaevAddDialog *ui) const override
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
~TimirbaevAutoCourier ()
Public Member Functions inherited from TimirbaevCourier
TimirbaevCourier ()
std::string GetFIO ()
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
~TimirbaevCourier ()
Private Attributes
std::string car_model
std::string car_number
Additional Inherited Members
Static Public Attributes inherited from TimirbaevCourier
static int MaxId = 0
Detailed Description
Definition at line 8 of file timirbaevautocourier.h.
Constructor & Destructor Documentation
TimirbaevAutoCourier()
TimirbaevAutoCourier::TimirbaevAutoCourier () inline
Definition at line 14 of file timirbaevautocourier.h.
: TimirbaevCourier() {}
References TimirbaevCourier::TimirbaevCourier().
~TimirbaevAutoCourier()
TimirbaevAutoCourier::~TimirbaevAutoCourier () inline
Definition at line 28 of file timirbaevautocourier.h.
{}
Member Function Documentation
CreateCourier()
void TimirbaevAutoCourier::CreateCourier (Ui::TimirbaevAddDialog * ui) override virtual
Reimplemented from TimirbaevCourier.
Definition at line 3 of file timirbaevautocourier.cpp.
{
    TimirbaevCourier::CreateCourier(ui);
    car_model = ui->lineEdit_5->text().toLocal8Bit().constData();
    car_number = ui->lineEdit_6->text().toLocal8Bit().constData();
}
References car_model, car_number, and TimirbaevCourier::CreateCourier().
EditCourier()
void TimirbaevAutoCourier::EditCourier (Ui::TimirbaevAddDialog * ui) const override virtual
Reimplemented from TimirbaevCourier.
Definition at line 30 of file timirbaevautocourier.cpp.
{
    TimirbaevCourier::EditCourier(ui);
    ui->label_5->setVisible(true);
    ui->lineEdit_5->setVisible(true);
    ui->lineEdit_5->setText(QString::fromLocal8Bit(car_model));
    ui->label_6->setVisible(true);
    ui->lineEdit_6->setVisible(true);
    ui->lineEdit_6->setText(QString::fromLocal8Bit(car_number));
}
References car_model, car_number, and TimirbaevCourier::EditCourier().
serialize()
template<class Archive> void TimirbaevAutoCourier::serialize (Archive & ar, const unsigned int version) inline
Definition at line 22 of file timirbaevautocourier.h.
{
        ar & boost::serialization::base_object<TimirbaevCourier>(*this);
        ar & car_model;
        ar & car_number;
    }
References car_model, and car_number.
ShowCourier()
void TimirbaevAutoCourier::ShowCourier (QPainter & painter, int & i) const override virtual
Reimplemented from TimirbaevCourier.
Definition at line 9 of file timirbaevautocourier.cpp.
{
    int y = i;
    TimirbaevCourier::ShowCourier(painter, i);
    int cellWidth = 150; // Ширина ячейки
    int cellHeight = 30; // Высота ячейки
    QRect cellRect5(5 * cellWidth + 10, y * cellHeight + 10, cellWidth, cellHeight);
    painter.drawText(cellRect5, Qt::AlignCenter, QString::fromLocal8Bit(car_model));
    QRect cellRect6(6 * cellWidth + 10, y * cellHeight + 10, cellWidth, cellHeight);
    painter.drawText(cellRect6, Qt::AlignCenter, QString::fromLocal8Bit(car_number));
}
References car_model, car_number, and TimirbaevCourier::ShowCourier().
ViewCourier()
void TimirbaevAutoCourier::ViewCourier (Ui::TimirbaevDialog * ui) const override virtual
Reimplemented from TimirbaevCourier.
Definition at line 20 of file timirbaevautocourier.cpp.
{
    TimirbaevCourier::ViewCourier(ui);
    ui->label_6->setVisible(true);
    ui->lineEdit_5->setVisible(true);
    ui->lineEdit_5->setText(QString::fromLocal8Bit(car_model));
    ui->label_7->setVisible(true);
    ui->lineEdit_6->setVisible(true);
    ui->lineEdit_6->setText(QString::fromLocal8Bit(car_number));
}
References car_model, car_number, and TimirbaevCourier::ViewCourier().
Member Data Documentation
car_model
std::string TimirbaevAutoCourier::car_model private
Definition at line 10 of file timirbaevautocourier.h.
Referenced by CreateCourier(), EditCourier(), serialize(), ShowCourier(), and ViewCourier().
car_number
std::string TimirbaevAutoCourier::car_number private
Definition at line 11 of file timirbaevautocourier.h.
Referenced by CreateCourier(), EditCourier(), serialize(), ShowCourier(), and ViewCourier().
The documentation for this class was generated from the following files:
timirbaevautocourier.h
timirbaevautocourier.cpp